
import { Toaster } from "sonner";
import "./globals.css";



export const metadata = {
  title: "Deal Drop App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster rishColors/>
      </body>
    </html>
  );
}
